
---
tomcat_path: /opt/SP/apps/tomcat
tomcat_tar_url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.10/bin/apache-tomcat-9.0.10.tar.gz
ROOT_FO_PATH: /opt/SP/apps/tomcat/webapps/ROOT
warfile: mobliestore-1-0.0.1-SNAPSHOT.war 
apps_path: /opt/SP/apps
